# active spring boot proflie
spring:
   proflie:
      active: dev
      

---
# common spring configuration

spring:



   # devtools
   devtools:
      livereload:
         enabled: true


   # MVC
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp


   # http (filter)
   http:
      encoding:
         charset: utf-8
         enabled: true
         forced: false
         forced-request: false
         forced-response: false


   # message resource (Internationalization)
   messages:
      always-message-format: true
      basename: messages/messages_ko
      encoding: utf-8


   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB


   # aop(@EnableAspectAutoProxy)
   aop.auto: true
   proxy-target-class: true

---
# production profile - sping boot configuration
spring:
   profile: production

   # datesource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://227.8.9.10:3306/webdb?characterEncoding=utf8
      username: webdb
      password: kakao@@
      initialSize: 10
      maxActive: 20
   

---
# dev profile - sping boot configuration
spring:
   proflie: dev

   # datesource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/webdb?characterEncoding=utf8
      username: webdb
      password: webdb
      initialSize: 10
      maxActive: 20

---
# server
server:
   port: 8080
   servlet:
      context-path: /mysite06

---
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

---
# logging
logging:
   config:classpath:logback.xml